### ISSUE TITLE
关于tg的群组无法获取消息的BUG

### ISSUE THREAD

**Issue by HideUsSaveUs** [OlivOS-Team/OlivOS#1]
![image](https://user-images.githubusercontent.com/39188665/129703477-b3eb8b36-b4a6-498a-b789-9f16318e282c.png)
在私聊发送有效，但是发送群聊无效

**Comment by lunzhiPenxil** [comment]
请先检查自己的BOT是否在群中具有访问群消息的权限：
![image](https://user-images.githubusercontent.com/26300331/129722445-d7f8edb3-c836-4734-a6d7-3ce3a8e41b63.png)
若为没有，请在Telegram官方处开启
设置路由应当为：Bot Settings -> Group Privacy -> Turn off
