### ISSUE TITLE
bug?: Dodo语音 Websocket 间隔固定时间后掉线

### ISSUE THREAD

**Issue by Ghost-chu** [OlivOS-Team/OlivOS#104]
### Describe

Dodo语音 Websocket 间隔固定时间后掉线

### To Reproduce

1. 添加 Dodo 机器人
2. Websocket 连接后，等待片刻后 Websocket 便会断开触发重连(约60秒)

### Expected behavior

Websocket 应该保持长连接

### Screenshots

![image](https://github.com/OlivOS-Team/OlivOS/assets/30802565/e4c167fe-8c80-4afd-a589-8011963b650e)

### Desktop (please complete the following information)

OS: Windows Server 2022
Version: 0.11.19(139)

### Smartphone (please complete the following information)

无

### Additional context

疑似心跳包问题？

**Comment by lunzhiPenxil** [comment]
https://github.com/OlivOS-Team/OlivOS/actions/runs/6719133471
请尝试最新action版本，是否还会存在该问题，最新版本中新增了对于V2接口的支持，并提供了V1接口的兼容，但我在调试过程中没有遇到你所说的情况，且我的生产环境也没有观察到你所说的问题

**Comment by lunzhiPenxil** [comment]
请进一步同步目前关于该问题的现状，目前该问题在开发侧未关查到复现，如果持续无法复现，我将会把这个议题标记为`not bug`并关闭

**Comment by Ghost-chu** [comment]
遗憾的是，此问题仍然存在。
但我已经不想折腾它了，它工作的相当差，其配套的 OneBot 协议插件测试 TRSS-Yunzai 等工具也根本无法连接上去。


现在，在 Nonebot 支持 DoDo 适配器后，我已不再使用 OlivOS。
倒霉的事情交给下一个用户吧。
&nbsp;


Ghost_chu
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2023年11月17日(星期五) 中午11:16
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [OlivOS-Team/OlivOS] bug?: Dodo语音 Websocket 间隔固定时间后掉线 (Issue #104)





 
请进一步同步目前关于该问题的现状，目前该问题在开发侧未关查到复现，如果持续无法复现，我将会把这个议题标记为not bug并关闭

**Comment by Ghost-chu** [comment]
我将此问题关闭，不再希望继续收到于此有关的后续邮件。  
我的设备是多网卡设备，但 Nonebot2 和 GenshinUID 等基于 WebSocket 互动的应用程序均工作良好，它们的 TCP/WS/WSS 连接都能正常建立并互发数据，仅 OlivOS 无法正常运行，我认为这是 OOS 的问题。  
既然开发侧无法复现该问题，我也不再使用 OlivOS，OlivOS 相比 Nonebot 等程序 bot 框架并没有显著优势。 我认可 OlivOS 团队的努力，但我不想继续在我不再使用的软件的支持问题上付出更多精力，我不再有真实的使用环境，因此也无从谈 debug。
