### ISSUE TITLE
关于dodo平台群聊消息事件的sender["user_id"]字段与qq不一致的问题

### ISSUE THREAD

**Issue by raininboat** [OlivOS-Team/OlivOS#19]
通过 plugin_event.data.sender["user_id"] 获取的用户 id 在qq平台下为 int 类型，而 dodo 中为 str 类型，建议进行统一
QQ 中 `sender` 字段内容
~~~jsonc
    "sender": {
        "nickname": "雨鸣于舟",
        "age": 0,
        "area": "",
        "card": "",
        "level": "",
        "role": "owner",
        "sex": "unknown",
        "title": "Master",
        "user_id": 16xxxx6761,         // 这里是整形
        "id": "16xxxx6761",
        "name": "雨鸣于舟"
    }
~~~
DODO 中 `sender` 字段内容
~~~jsonc
"sender": {
        "nickname": "雨鸣于舟",
        "user_id": "18xxxx785",        //  这里是字符串
        "id": "18xxxx785",
        "name": "雨鸣于舟",
        "sex": "unknown",
        "age": 0
    }
~~~

**Comment by lunzhiPenxil** [comment]
按照标准而言，`sender`结构体中只有`id`与`name`为必然提供，其余为尽量提供，这一点在onebot中是明确被提出的。
至于你所说的`ID`类型是整形和字符串混杂，这个特点是之前的`81`版本接口的特性，新版本`94`已经将所有`ID`转化为`str`类型，详情可见[接口版本推进到94等多项改动](https://github.com/OlivOS-Team/OlivOS/commit/2e9e54f11c281eae0c975d8c2895aa44cd7bfb99)

**Comment by lunzhiPenxil** [comment]
目前的建议是`id`仅仅以`id`条目为准，`user_id`条目仅仅作为向下兼容的设计提供，在可预见的未来将会被移除
