### ISSUE TITLE
api.py 中 PARA.node.data_T入参有误

### ISSUE THREAD

**Issue by raininboat** [OlivOS-Team/OlivOS#4]
如图
![YY 3%(4LA_OD)W(RAS$4%FG](https://user-images.githubusercontent.com/74845844/135969067-2cff0def-da3d-4fcd-818d-a97b1ce07b70.png)
![O@PCQBN 9TQ $G$H5I9(BWL](https://user-images.githubusercontent.com/74845844/135969077-646f648f-8c18-4f57-b72b-c3a8a766a2cf.png)

**Comment by raininboat** [comment]
不过似乎这个cq码也不能直接使用，需要单独api支
![B06CUW4@BQ WWB_ED6%}LQ1](https://user-images.githubusercontent.com/74845844/135970209-750b97d9-2455-4fc3-9ba2-cc5cc7047e24.png)
持

**Comment by lunzhiPenxil** [comment]
事实上是，目前只应用了string模式的接口调用，合并转发相关接口需要消息段模式的接口调用，目前这部分的开发停留在仅SDK阶段，短期内不考虑支持。

**Comment by lunzhiPenxil** [comment]
简单来说，我在onebotSDK中预留了消息段调用配套的接口，只是目前暂时没有迫切需求来做这个事情，等主要功能稳定之后可以来做这个事情。

**Comment by lunzhiPenxil** [comment]
当前关闭，等待开发计划推进到此处时重新打开。
