### ISSUE TITLE
Add password(tripcode) option to hackchatSDK

### ISSUE THREAD

**Issue by MaggieLOL** [OlivOS-Team/OlivOS#78]
希望能在hackchatSDK中加入密码选项（password），方法是在join包中加入password字段，以获得一个tripcode(识别码)。这（tripcode）是在Hack.chat中唯二鉴别身份的方式（hash也可以，但hash基于IP计算，人们更倾向于使用tripcode）

~~一句废话，Hack.chat用户们很高兴有大佬给hc做了一个成熟的bot框架，希望您能和我们一起来交流：https://hc.thz.cool/?your-channel 或使用官方客户端 https://hack.chat/?your-channel~~

**Comment by lunzhiPenxil** [comment]
非常合理的提议，已加入到开发计划中
