### ISSUE TITLE
[已解决]键名超过24个字符的helpdoc无法被模糊搜索

### ISSUE THREAD

**Issue by HadalFauna** [OlivOS-Team/OlivOS#89]
**Describe the bug**

当自定义帮助文档词条的词条名超过24个字符时，无法出现在模糊搜索的结果池中，仅在输入完整词条名时可以获得词条内容

**To Reproduce**
1. 用任意方法导入词条名（键名）超过24个字符的自定义帮助文档词条，如"一二三四五六七八九十甲乙丙丁戊己庚辛壬癸子丑寅卯辰巳午未申酉":"TEST"
2. 用模糊关键字搜索该词条，如“.help申酉”
3. 将返回“未找到匹配条目”
4. 用完整关键字搜索该词条，如“.help一二三四五六七八九十甲乙丙丁戊己庚辛壬癸子丑寅卯辰巳午未申酉”时，才能正常返回词条内容“TEST”

**Expected behavior**

期望返回以下内容：

已为你找到以下以下相似条目:
1.一二三四五六七八九十甲乙丙丁戊己庚辛壬癸子丑寅卯辰巳午未申酉
请输入序号以查看对应选项

**Screenshots**

使用的英文测试json和测试效果
![QQ截图20230619203843](https://github.com/OlivOS-Team/OlivOS/assets/113657202/57c6746e-decb-47b3-aeec-807dd38b12e3)
![QQ图片20230110154222](https://github.com/OlivOS-Team/OlivOS/assets/113657202/648089ee-1ff2-4481-aab1-b389e4542e4d)

使用的中文测试json和测试效果
![QQ截图20230619204831](https://github.com/OlivOS-Team/OlivOS/assets/113657202/6881f69d-2c94-43cd-b6a8-ef3d2bd6c306)
![QQ截图20230619205005](https://github.com/OlivOS-Team/OlivOS/assets/113657202/9a09f20e-7e52-4895-9756-20fab39ac786)

**Additional context**
使用的版本：
[OlivaDice] - [Init] - 当前版本为[3.3.15(1065)]
欢迎使用 青果核心交互栈 OlivOS 0.11.9(129)

已在论坛和Issues中搜索，已查阅手册，暂未找到与遇到的问题有关的内容（手册里的HelpMode配置项已经失效）
<del>发完才发现好像应该发到OlivaDiceCore那边<del>

至于干啥要24+个字符那么长的条目名，是因为玩的规则没有全汉化所以存了一些生肉规则书英文名的词条，然而英文的话一下就超过24字符了orz
![QQ图片20230624232705](https://github.com/OlivOS-Team/OlivOS/assets/113657202/d4238346-97bb-4ed4-bfff-725bf3b3ff95)

**Comment by lunzhiPenxil** [comment]
配置项中有一个名为`helpRecommendGate`的选项是用于控制这个特性的，这是为了避免对不合理长度的词条进行不必要的模糊匹配的设计，主要目的是为了节约性能，你可以根据需要来进行调整
![image](https://github.com/OlivOS-Team/OlivOS/assets/26300331/e25f75bf-7d4d-4df8-841a-641cc2e885e4)

**Comment by HadalFauna** [comment]
> 

噢噢，不是BUG就好，感谢回复
我在网页版手册的配置项那里没找到这一项的说明，可能是漏写了

**Comment by HadalFauna** [comment]
> 配置项中有一个名为`helpRecommendGate`的选项是用于控制这个特性的，这是为了避免对不合理长度的词条进行不必要的模糊匹配的设计，主要目的是为了节约性能，你可以根据需要来进行调整 ![image](https://user-images.githubusercontent.com/26300331/249229516-e25f75bf-7d4d-4df8-841a-641cc2e885e4.png)

噢噢，不是BUG就好，感谢回复
我在网页版手册的配置项那里没找到这一项的说明，可能是漏写了

**Comment by lunzhiPenxil** [comment]
> > 配置项中有一个名为`helpRecommendGate`的选项是用于控制这个特性的，这是为了避免对不合理长度的词条进行不必要的模糊匹配的设计，主要目的是为了节约性能，你可以根据需要来进行调整 ![image](https://user-images.githubusercontent.com/26300331/249229516-e25f75bf-7d4d-4df8-841a-641cc2e885e4.png)
> 
> 噢噢，不是BUG就好，感谢回复 我在网页版手册的配置项那里没找到这一项的说明，可能是漏写了

确实是没有写，这是我们的疏忽
